stages:
- deploy

jobs:
- name: deploy:staging
  stage: deploy
  image: sunci/ruby:2.5.1
  script:
  - echo done
  - sleep 10
  only:
    branches:
    - master
  except:
    events:
    - pull_request
